services:
  app:
    build:
      context: .
      target: app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      CHROMIUM_URL: http://chromium:9222
      TZ: Europe/Warsaw
    depends_on:
      chromium:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    labels:
      traefik.docker.network: coolify

  chromium:
    build:
      context: .
      target: chromium
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9222/json/version || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "2m"
        max-file: "3"
