services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped
    networks: [currencyrates]
    links:
      - chromium
    environment:
      CHROMIUM_URL: http://chromium:9222
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1
      interval: 1s
    depends_on:
      chromium:
        condition: service_healthy
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

  nginx:
    build:
      context: .
      target: nginx
    restart: unless-stopped
    networks: [currencyrates]
    depends_on:
      chromium:
        condition: service_healthy
      api:
        condition: service_healthy
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    labels:
      traefik.docker.network: coolify

  chromium:
    build:
      context: .
      target: chromium
    networks: [currencyrates]
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9222/json/version || exit 1
      interval: 3s
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: on-failure

networks:
  currencyrates:
    external: false
