version: "3.8"

services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped
    networks: [currencyrates]
    links:
      - chromium
    environment:
      CHROMIUM_URL: http://chromium:9222
    depends_on:
      chromium:
        condition: service_healthy

  nginx:
    build:
      context: .
      target: nginx
    restart: unless-stopped
    networks: [proxy, currencyrates]
    depends_on:
      chromium:
        condition: service_healthy
      api:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.http.routers.currencytracker.entrypoints: http
      traefik.http.routers.currencytracker.rule: Host(`currency.plgn.xyz`)
      traefik.http.middlewares.currencytracker-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.currencytracker.middlewares: currencytracker-https-redirect
      traefik.http.routers.currencytracker-secure.entrypoints: https
      traefik.http.routers.currencytracker-secure.rule: Host(`currency.plgn.xyz`)
      traefik.http.routers.currencytracker-secure.tls: true
      traefik.http.routers.currencytracker-secure.service: currencytracker
      traefik.http.services.currencytracker.loadbalancer.server.port: 80
      traefik.docker.network: proxy

  chromium:
    container_name: chromium
    image: "zenika/alpine-chrome:latest"
    networks: [currencyrates]
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9222/json/version || exit 1
      interval: 10s
    command: [ chromium-browser, --headless, --disable-gpu, --no-sandbox, --remote-debugging-port=9222, --remote-debugging-address=0.0.0.0, about:blank ]

networks:
  currencyrates:
    external: false
  proxy:
    external: true
